- x/gov/keeper/common_test.go
- x/gov/keeper/deposit_test.go
- x/gov/keeper/hooks_test.go
- x/gov/keeper/keeper_test.go
- x/gov/keeper/tally.go
- x/gov/keeper/tally_test.go
- x/gov/keeper/vote_test.go
Cherry pick of https://github.com/cosmos/cosmos-sdk/pull/17142 with some updates that improves the mocking of the staking module. 
Mocking this module is deceptively complex, due to the shares system. I would better have integration tests for testing the tally, like `cosmos-sdk/tests/integration/gov`, but unfortunately these are difficult to migrate out of the cosmos-sdk (if not impossible).
> test: add some tally tests

- x/gov/keeper/tally.go
This type was used to hold the validator vote and its delegation
deductions. Now that vote inheritance is disabled, we don't need to hold
these values any more, we can just use the type returned by the staking
keeper.
> refactor(gov): remove usage of v1.ValidatorGovInfo 

- x/gov/keeper/msg_server_test.go
- x/gov/types/v1/params.go
- x/gov/types/v1/params_legacy.go
- x/gov/types/v1beta1/params.go
Prevents setting a voting period less than 3 weeks 
It seems though that in simulation - at genesis time at least - lower values are ok (and they should) since `ValidateBasic` is not called.
> feat(x/gov): hard min voting period to 3 weeks

- tests/e2e/chain.go
- tests/e2e/e2e_bank_test.go
- tests/e2e/e2e_distribution_test.go
- tests/e2e/e2e_evidence_test.go
- tests/e2e/e2e_exec_test.go
- tests/e2e/e2e_feegrant_test.go
- tests/e2e/e2e_gov_test.go
- tests/e2e/e2e_rest_regression_test.go
- tests/e2e/e2e_setup_test.go
- tests/e2e/e2e_slashing_test.go
- tests/e2e/e2e_staking_test.go
- tests/e2e/e2e_test.go
- tests/e2e/e2e_vesting_test.go
- tests/e2e/http_util.go
- tests/e2e/query_test.go
- x/gov/keeper/grpc_query.go
- x/gov/keeper/grpc_query_test.go
The main benefit of this change is to print the node logs when no blocks are produced. For that, because the nodes are running in a docker container, the docker API logs is requested.
Also:
- call `t.Run()` appropriately: some calls were irrelevant, like when they are used to execute a command which is a part of a test case.
- rename test cases appropriately
- print a hint "is the docker image up-to-date?" when the node don't produce block, because most of the time it is the reason.
- increase speed by removing some sleeps and reducing the `Eventually` tick parameter
- improve http request error handling by checking the response status, and eventually retry if the status is "Service Unavailable"
- add test on gov param change
- update `/atomone.gov.v1.Params` query so it doesn't return an …
> test(e2e): improvements

- .github/workflows/release.yml
- .goreleaser.yml
- Makefile
- README.md
- add make build-ledger
- fix CI env set TM_VERSION
- reinforce go version to go1.21.13
- build will exit if go version doesn't match exactly
- print instruction to run with specific go version
- add `make print_required_go_version` so CI can fetch the information
> chore: make build-ledger, fix reproducible builds, reinforce go version

- README.md
The registry repo has been replaced finally by the atom.one website. We should also delete that repo.
> doc: replace registry link

- Makefile
Add an info log line when building without ledger support to inform the user of the presence of the appropriate target / env variable.
> chore: add info log when building with Ledger support disabled

- app/app.go
- app/upgrades/v2/constants.go
- app/upgrades/v2/upgrades.go
- x/photon/keeper/msg_server.go
- x/photon/keeper/msg_server_test.go
- x/photon/types/errors.go
Relates to #44
- perform module migration to add the photon module in the upgrade module version map
- register the photon denom metata in the bank module
- add a storeloader for the photon module (required for all new modules)
> feat(x/photon): migration

- UPGRADING.md
Relates to #44 
I realized that the running relayers would also have to update their config to use PHOTON for the fees, or else all txs would be rejected. So added a section to cover that part.
Also added a kind remind for validators that have `authz` transactions submitted periodically (for example validators who support services like restake) to update the tx fee denom as well.
> docs(upgrade): add relayer config change section

- Dockerfile
- UPGRADING.md
- contrib/Dockerfile.test
- contrib/devdeps/go.mod
- go.mod
Go is being  carefully upgraded in SDK chains because of issues with state sync between nodes (although there is no evidence of this as far as I have investigated).
This change upgrades Go from 1.21.13 to 1.22.10 (the latest 1.22 release). Go 1.22 is already being used in the Gaia mainnet and no problems of state sync have been reported.
Once merged, this will allow the upgrade of cometbft which will fix 2 vulnerabilities raised by govuln.
The Upgrading file has been lazily updated, knowing that the merge of #57 will bring more context.
> chore: bump go to 1.22

- x/gov/genesis_test.go
- x/gov/keeper/min_deposit_test.go
- x/gov/keeper/msg_server_test.go
- x/gov/types/v1/genesis_test.go
- x/gov/types/v1/params.go
> fix(x/gov): α must be strictly between 0 and 1

- docs/architecture/adr-003-governance-proposal-deposit-auto-throttler.md
ADR for the implementation of the min deposit throttling, with notes on also the min initial deposit.
Implementation is at https://github.com/atomone-hub/atomone/pull/69
[Rendered version](https://github.com/atomone-hub/atomone/tree/docs/adr-dyamic-deposit/docs/architecture/adr-003-governance-proposal-deposit-auto-throttler.md)
> docs: ADR-003 Governance Proposal Deposit Auto-Throttler

- x/photon/README.md
As per the title, add the `x/photon` module documentation with references to the photon ADR
> docs(x/photon): add module documentation

- .github/workflows/release-sims.yml
- .github/workflows/sim-label.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- x/gov/keeper/migrations.go
- x/gov/migrations/v5/store.go
- x/gov/migrations/v5/store_test.go
- x/gov/module.go
I had to change the CI `action/cache` version because the version was deprecated.
> chore(x/gov): add module migration to initialize new params

- app/app.go
- post/post.go
- x/feemarket/ante/fee.go
- x/feemarket/post/expected_keeper.go
- x/feemarket/post/update_state.go
- x/feemarket/types/state.go
as the title suggests.
change to 0 fees in simulation to allow for no bank balances in sim, as per https://github.com/skip-mev/feemarket/pull/138
I also re-added the postHandler since wrongly removed also the logic to updated consumed gas in the module state
missing backporting tests from https://github.com/skip-mev/feemarket/pull/138
> feat(x/feemarket): sync with `skip/feemarket` `v1.1.1` (except tests) and re-add postHandler

- .github/workflows/release-sims.yml
- .github/workflows/sim-label.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
bump dependency to fix github actions errors
> chore: bump `actions/cache` in github actions

- .github/workflows/release-sims.yml
- .github/workflows/sim-label.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
Same as #94 but targeting the `release/v1.x` branch
> chore: bump `actions/cache` in github actions for `release/v1.x` branch

- CHANGELOG.md
- go.mod
- go.sum
Upgrade ibc-go to v7.10.0 to fix [ISA-2025-001](https://github.com/cosmos/ibc-go/security/advisories/GHSA-4wf3-5qj9-368v)
> deps: upgrade ibc-go to v7.10.0

- CHANGELOG.md
- x/gov/keeper/grpc_query_test.go
- x/gov/migrations/v3/convert.go
Converter was returning an error when the v1 proposal has no messages, which can be considered as a bug since the v1 API allows to submit proposals without messages.
The fix handles such proposal and turn them into v1beta1 text proposal.
Additionnaly to unit tests, a test was made with a local node, ensuring it is now possible to request a v1 proposal that has no messages using a v1beta1 request.
> fix(x/gov): proposal v1 to v1beta1 converter

- x/gov/keeper/grpc_query_test.go
- x/gov/keeper/keeper_test.go
- x/gov/keeper/msg_server_test.go
- x/gov/keeper/proposal_test.go
State was not reinitialized between test cases, which was confusing for some scenario and forced sometimes to reset things like the deposit throttling.
The fix consists only of calling `suite.reset()` in `KeeperTestSuite.SetupSubTest()`, the other changes removes any correlation previously made by the test cases about this common state.
> test(x/gov): independent cases in KeeperTestSuite

- .github/workflows/test.yml
- Makefile
- contrib/localnet/proposal_legacy_param_change.json
- contrib/localnet/proposal_text.json
- contrib/localnet/proposal_upgrade.json
- docs/README.md
`start-localnet-ci` is renamed `localnet-start` because I want the target to be more usable and not namely tied to CI processes. Some other target `localnet-*` are added to simplify some other tasks like submitting proposals.
Target itself is improved by adding photon balances to the genesis accounts, enabling REST API and reducing the voting period to 5min.
A short documentation is added to describe how to test a chain upgrade using a gov software upgrade proposal.
> test: revamp localnet Makefile

- docs/architecture/adr-002-photon-token.md
Fix minor typos in ADR
Same changes as https://github.com/atomone-hub/atomone-docs/pull/10
---
*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*
I have...
*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*
I have...
> docs: fix typos in `x/photon` ADR

- docs/architecture/adr-002-photon-token.md
Changed ADR 002:
"The only way to `get` PHOTONs" to "the only way to `mint` PHOTONs."
> docs: Updated ADR 002

- app/keepers/keys.go
The key was initially kept to perform the deletion of the store, but then the node is not able to restart because the store was expected to have the key.
Error: `failed to load latest version: failed to load latest version: version of store crisis mismatch root store's version; expected 45 got 0; new stores should be added using StoreUpgrades`
> fix: remove the crisis module key from keys list

- tests/e2e/e2e_exec_test.go
- tests/e2e/e2e_photon_test.go
- x/photon/simulation/operations.go
- x/photon/types/msgs.go
This PR fixes an issue that could arise if a user typed the wrong denom when issuing a photon mint transaction, for example:
`atomoned tx photon mint 1000`**wrongdenom**` -y --home=/path/to/home --fees=330000uatone --keyring-backend=test --output=json  --from=wallet --broadcast-mode=sync --chain-id=chain_name`
Even though the transaction is incorrect, without this fix, the fees would be charged to the user.
> fix: ensures correct denom when minting photon

- tests/e2e/e2e_ibc_test.go
- tests/e2e/e2e_setup_test.go
- tests/e2e/e2e_test.go
This PR splits the setup and teardown of the e2e tests into phases. The first setup phase is executed at the beginning of any e2e test and initializes only one chain, without setting up the secondary chain and IBC. The second phase is lazily executed when IBC is needed and performs the IBC setup. 
For most of the tests IBC is not required, and this PR gives substantial speedup on single e2e tests (see below).
The only additional requirement for this PR to work is that any tests that requires IBC to be setup, should start with a call to `s.ensureIBCSetup()`.
Split Setup Phases times:
All e2e tests: 390s
TestPhoton e2e tests: 13s
Current e2e times:
All e2e tests: 469s
TestPhoton e2e tests: 94s
> test(e2e): split e2e test setup phase and separated IBC setup

- UPGRADING.md
- x/photon/README.md
In particular, I want to draw your attention to the change I made to gas prices. I decided to talk about the photon conversion rate and how it should affect the value of the photon gas price chosen by validators and relayers.
I'm not sure if this is the correct position, but I wanted to open the discussion on it.
Basically I see 2 ways of defining gas prices :
- `gas-prices=0.01uatone,0.09uphoton` : we explicitely use the conversion rate to ensure  a fair gas price between the 2 different tokens.
- `gas-prices=0.01uatone,0.01uphoton`: this creates an imbalance between the 2 fees, basically fees are cheaper if you use photon.
(Note that I chose solution 1 in the PR because I had to choose one or the other, not because I think 1 is the best approach)
I actually see a benefit for 2: it …
> docs: v2 upgrade instructions update

- x/feemarket/AIMD.md
Description
The documentation AIMD.md is not in line with the [code](https://github.com/atomone-hub/atomone/blob/feat/x/feemarket/x/feemarket/types/state.go#L109):
`	if avg.LTE(params.Gamma) || avg.GTE(math.LegacyOneDec().Sub(params.Gamma)) {`
> chore(x/feemarket): Fixed lt and gt in documentation to reflect the implementation

- UPGRADING.md
Final recommendation after discussions:
- Photon gas price should be 9x times higher than atone price.
- Current atone gas price at 0.025 is not too high.
> docs(upgrading): gas price recommendation

- x/feemarket/README.md
- x/feemarket/fuzz/aimd_eip1559_test.go
- x/feemarket/fuzz/eip1559_test.go
- x/feemarket/keeper/feemarket.go
- x/feemarket/keeper/feemarket_test.go
- x/feemarket/types/state.go
- x/feemarket/types/state_fuzz_test.go
- x/feemarket/types/state_test.go
The feemarket module and tests improperly use the terms `Size` and `Utilization` to refer to `Gas`.
This PR refactors these instances where appropriate.
> chore(x/feemarket): Refactored Utilization and Size to Gas in feemarket module

- x/feemarket/README.md
As per the title, forgot to update the docs to reflect the addition of the new parameter before merging the feemarket PR.
Fixing it here.
> chore(x/feemarket): update README.md

- docs/architecture/adr-004-nakamoto-bonus.md
- Replace `*` per `\times`
- Remove unecessary `.` at the end of some formulas
- Fix rendering of \eta definition
> docs(adr): fix typo in Nakamoto bonus

- x/gov/types/unified_diff.go
- x/gov/types/unified_diff_test.go
As per PR title, add checks to catch and error on malformed unified diffs (with hunks going outside the actual length of the source document).
> fix(x/gov): add boundary checks for unified diffs

- Makefile
- app/upgrades/v3/upgrades.go
- contrib/localnet/proposal_upgrade.json
- x/photon/keeper/grpc_query.go
- x/photon/keeper/keeper.go
- x/photon/keeper/msg_server.go
- x/photon/keeper/resolver.go
As the title suggests, this PR creates v3/upgrade code to mint photon using 90% of atone funds from both the community pool as well as the designated address of the Treasury DAO
> feat(v3/upgrade): add v3 upgrade code to mint photon from 90% of atone funds of Community Pool and Treasury DAO address

- x/feemarket/types/params.go
- x/feemarket/types/params_test.go
The `TargetBlockUtilization` parameter should be prevented from being set to 0. There are other ways to disable the feemarket making this one sort of redundant.
Moreover, this would prevent a division by 0 panic (caught by the error manager, so no chain halt, but still annoying)
> fix(feemarket): prevent setting `TargetBlockUtilization` to 0

- x/gov/keeper/proposal.go
Although this is almost impossible in realistic scenarios, we still want to catch potential failures of `cdc.UnpackAny` for an `sdk.Msg` in a proposal when calling `ProposalKinds`.
Therefore, an else statement catches this failure and assumes the default `v1.ProposalKindAny`.
> chore(gov): gracefully handle failure to unpack a `sdk.Msg` in `ProposalKinds`

- tests/e2e/e2e_gov_test.go
- tests/e2e/e2e_setup_test.go
- tests/e2e/e2e_test.go
- tests/e2e/query_test.go
E2E tests for the dynamic quorum feature
Closes:  #145 
(with PR #146)
Based on PR #152
> test(e2e): dynamic quorum e2e tests

- tests/e2e/e2e_gov_test.go
- x/gov/keeper/min_deposit_test.go
- x/gov/keeper/min_initial_deposit_test.go
- x/gov/keeper/msg_server_test.go
- x/gov/types/v1/params.go
This PR fixes the generation of params for the dynamic deposit in `x/gov` when using the CLI command `init genesis` if another denom is passed with the flag `--default-denom`.
The correct denom is now used instead of always picking the default one (`stake`) regardless.
> fix(gov): fix CLI command `init genesis` param generation for dynamic deposit

- tests/e2e/e2e_dynamicfee_test.go
The gas price change e2e test for the  `dynamicfee` module  has a loop that waits until the value of the learning rate goes below the maximum learning rate.
This loop is incorrect, as the learning rate will increase by waiting (average block utilization goes to 0, which is far from the target block utilization, hence additive increase is used to update the learning rate).
This check was not crucial to the test - that only verifies that there is a gas price increases after a big enough transaction - therefore it can be removed.
> Fixed dynamicfee gas price change e2e test

- .golangci.yml
- CHANGELOG.md
- Makefile
- app/app.go
- app/keepers/keepers.go
- client/docs/embed.go
- contrib/devdeps/go.mod
- contrib/devdeps/go.sum
- contrib/devdeps/tools.go
- contrib/githooks/pre-commit
- contrib/githooks/precommit
- go.mod
Closes: NA
`go:embed` was introduced in go `v1.16`, and removes the need to use external libraries such as statik. This PR removes the direct dependeny and usage of `statik` and replaces it with the built-in `go:embed`
This is confirmed working with the lastest build from `main` when running
```shell
atomoned start --api.enable=true --api.swagger=true
```
---
*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*
I have...
*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*
I have...
> refactor(swagger): use go:embed instead of statik for UI assets

- tests/e2e/e2e_gov_test.go
- tests/e2e/e2e_setup_test.go
- tests/e2e/query_test.go
The dynamic deposit feature makes the required minimum initial deposit and overall deposit dynamic. E2E tests use for both a fixed amount, this can cause the tests to fail if the fixed amounts used are less than the dynamic amounts required.
This PR adds queries for the dynamic deposit values and uses the updated values for the e2e tests.
> fix(e2e): E2E tests do not fetch dynamic deposit values

- CHANGELOG.md
- x/gov/migrations/v5/store.go
- x/gov/migrations/v5/store_test.go
The migration use the default params to feed the minDeposit and minInitialDeposit, but they are using the sdk.DefaultBondDenom which is `stake`.
The fix simply udpates the denom of each to use `uatone`.
> fix(x/gov): wrong denom for min[Initial]Deposit

- Makefile
- UPGRADING.md
Updating the guide for the v3 upgrade. 
NOTE: This PR targets the `release/v3.x` branch and will be backported to `main` once approved.
> docs: v3 UPGRADING

- tests/e2e/e2e_exec_test.go
- tests/e2e/e2e_photon_test.go
- x/photon/client/cli/tx.go
As the title suggests, backport #222 to the `release/v3.x` branch
> fix(x/photon/cli): add `to_address` arg to CLI tx `GetTxMintPhotonCmd` (backport #222)

- x/photon/keeper/keeper.go
Since I'm sick and tired of people reporting this as an issue because they did not understand the fundamental assumption that the burned token is the denom token and thus some of it need to be staked (i.e. locked) to be able to produce blocks meaning it can't go to zero literally ever, I added a clarification and a panic.
Hopefully this should discourage raising the same (wrong) issue in the future.
> chore(x/photon): clarify impossibility of division by zero in `PhotonConversionRate`
